[package]
name = "ymb_welcome_gui"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
eyre.workspace = true
bevy.workspace = true
ymb_args.workspace = true
ymb_logs.workspace = true