[package]
name = "ymb_windy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
eyre.workspace=true
clap.workspace=true
windows.workspace=true
widestring.workspace=true
bstr.workspace=true