[package]
name = "ymb_inspector_plugin"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bevy.workspace = true
bevy-inspector-egui.workspace = true