[package]
name = "ymb_host_cursor_position_plugin"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
ymb_windy.workspace=true
bevy.workspace=true
windows.workspace=true
holda.workspace=true